book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('read/', views.read_book, name='read_book'),
    path('detail/read/<int:book_primary_key>/', views.read_book_detail, name='read_book_detail'),
    path('create/', views.create_book, name='create_book'),
    path('update/<int:book_primary_key>/', views.update_book, name='update_book'),
    path('author/add/', views.add_author, name='add_author'),
    path('author-in-list/add/<int:primary_key>/', views.add_author_in_author_list, name='add_author_in_author_list'),
]

django_library_management/urls.py
from django.contrib import admin
from django.urls import path, include
# Imports for showing images.
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('__reload__/', include('django_browser_reload.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user-profile/', include('user_profile.urls')),
    path('address/', include('address.urls')),
    path('course/', include('course.urls')),
    path('thesis/', include('thesis.urls')),
    path('book/', include('book.urls')),
    path('suggestion/', include('suggestion.urls')),
    path('borrow-book/', include('borrow_book.urls')),
    path('review/', include('review.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

thesis/urls.py
from django.urls import path
from . import views

app_name = 'thesis'

urlpatterns = [
    path('', views.view_thesis, name='view_thesis'),
    path('detail/<int:primary_key>/', views.view_thesis_detail, name='view_thesis_detail'),
    path('add/', views.add, name='add'),
    path('edit/<int:primary_key>/', views.edit, name='edit'),
    path('author/add/', views.add_author, name='add_author'),
    path('author-in-list/add/<int:primary_key>/', views.add_author_in_author_list, name='add_author_in_author_list'),
    path('view_file/<str:file_location>/', views.view_file, name='view_file'),
]

thesis/models.py
from django.db import models
from course.models import Course

class Author(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='thesis_author_images', default='default_profile_image.jpg')
    course = models.ForeignKey(Course, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

class Thesis(models.Model):
    title = models.CharField(max_length=255)
    date_published = models.DateField(null=True)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    image = models.ImageField(upload_to='thesis_images', default='default_thesis_image.jpg')
    file = models.FileField(upload_to='thesis_files', default='testing.pdf')

    def __str__(self):
        return self.title

class Author_List(models.Model):
    thesis = models.ForeignKey(Thesis, related_name='thesis_id', on_delete=models.PROTECT)
    author = models.ForeignKey(Author, related_name='author_id', on_delete=models.PROTECT)


    

    

thesis/forms.py
from django import forms
from .models import Thesis, Author, Author_List

INPUT_CLASSES = 'rounded-r-lg bg-gray-50 border border-gray-300 text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
SELECT_AREA = 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
TEXT_AREA = 'block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
FOR_IMAGE = 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400'
CHECKBOX = 'w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600'

class ThesisForm(forms.ModelForm):
    class Meta: 
        model = Thesis
        fields = ['title', 'date_published', 'course', 'image', 'file']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'date_published' : forms.SelectDateWidget(years=range(1500, 2999), attrs={
                'class': SELECT_AREA,
            }),
            'course': forms.Select(attrs={
                'class': INPUT_CLASSES,
            }),
            'image': forms.FileInput(attrs={
                'class': FOR_IMAGE,
            }),
            'file': forms.FileInput(attrs={
                'class': FOR_IMAGE,
            }),
        }

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'image', 'course']
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'last_name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'course': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': FOR_IMAGE
            }),
        }

class AuthorListForm(forms.ModelForm):
    class Meta:
        model = Author_List
        fields = ['author']
        widgets = {
            'author': forms.Select(attrs={
                'class': INPUT_CLASSES,
            })
        }

thesis/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import FileResponse, Http404
from core.decorators import allow_certain_groups
from course.models import Course
from .models import Thesis, Author_List
from .forms import ThesisForm, AuthorForm, AuthorListForm

@login_required
def view_thesis(request):
    theses = Thesis.objects.all()
    courses = Course.objects.all()

    query = request.GET.get('query', '')
    course_id = request.GET.get('course', 0)

    if course_id:
        theses = Thesis.objects.filter(course=course_id)
    if query: 
        theses = Thesis.objects.filter(Q(title__icontains=query))
    return render(request, 'thesis/view_thesis.html', {
        'title': 'Thesis',
        'is_staff': request.is_staff,
        'theses': theses,
        'courses': courses,
    })

@login_required
def view_thesis_detail(request, primary_key):
    thesis = get_object_or_404(Thesis, pk=primary_key)
    authors = Author_List.objects.filter(thesis_id=primary_key)
    
    return render(request, 'thesis/view_thesis_detail.html', {
        'title': 'Thesis Detail',
        'thesis': thesis,
        'authors': authors,
        'is_staff': request.is_staff,
    })

@login_required
def view_file(request, file_location):
    try:
        return FileResponse(open(file_location, 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404()
    
@login_required
@allow_certain_groups(['staff'])
def add(request):
    if request.method == 'POST':
        form = ThesisForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Success! The thesis has been added.')
            return redirect('thesis:view_thesis')
    else:
        form = ThesisForm()
    return render(request, 'thesis/form.html', {
        'title': 'Thesis',
        'form': form,
        'is_staff': request.is_staff,
    })

@login_required
@allow_certain_groups(['staff'])
def edit(request, primary_key):
    thesis = get_object_or_404(Thesis, pk=primary_key)
    if request.method == 'POST':
        form = ThesisForm(request.POST, request.FILES, instance=thesis)
        if form.is_valid():
            form.save()
            messages.success(request, 'Success! The thesis has been edited.')
            return redirect('thesis:detail', primary_key=primary_key)
    else:
        form = ThesisForm(instance=thesis)
    return render(request, 'thesis/form.html', {
        'title': 'Edit Thesis',
        'form': form,
        'is_staff': request.is_staff,
    })

@login_required
@allow_certain_groups(['staff'])
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST, request.FILES)
        if form.is_valid():
            author = form.save(commit=False)
            author.name = f"{request.POST['first_name'].capitalize()} {request.POST['last_name'].capitalize()}"
            author.save()
            messages.success(request, 'Success! The author has been added.')
            return redirect('thesis:view_thesis')
    else:
        form = AuthorForm()

    return render(request, 'thesis/form.html', {
        'title': 'Add Author',
        'form': form,
        'is_staff': request.is_staff,
    })

@login_required
@allow_certain_groups(['staff'])
def add_author_in_author_list(request, primary_key):
    if request.method == 'POST':
        form = AuthorListForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.thesis_id = primary_key
            author.save()
            messages.success(request, 'Success! The author has been added to the book\'s author list.')
            return redirect('thesis:detail', primary_key=primary_key) 
    else:
        form = AuthorListForm()
    return render(request, 'thesis/form.html', {
        'title': 'Add Author in Author List',
        'form': form,
        'is_staff': request.is_staff,
    })

thesis/templates/thesis/view_thesis.html
{% extends 'core/base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<div class="w-full mb-4">
    <form method="get" action="{% url 'thesis:view_thesis' %}">
        <div class="flex">
            <label for="search-dropdown" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search
                Thesis</label>
            <button id="dropdown-button" data-dropdown-toggle="dropdown"
                class="flex-shrink-0 z-10 inline-flex items-center py-2.5 px-4 text-sm font-medium text-center text-gray-900 bg-gray-100 border border-gray-300 rounded-l-lg hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-gray-700 dark:text-white dark:border-gray-600"
                type="button">
                All courses
                <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                    viewBox="0 0 10 6">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="m1 1 4 4 4-4" />
                </svg>
            </button>
            <div id="dropdown"
                class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown-button">
                    {% if courses %}
                    {% for course in courses %}
                    <li>
                        <a href="{% url 'thesis:view_thesis' %}?query={{ query }}&course={{ course.id }}" type="button"
                            class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">{{
                            course.name }}</a>
                    </li>
                    {% endfor %}
                    {% else %}
                    <li>
                        <p
                            class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                            Empty Category</p>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div class="relative w-full">
                <input type="text" name="query" value="{{ query }}" id="search-dropdown"
                    class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-r-lg border-l-gray-50 border-l-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-l-gray-700  dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-blue-500"
                    placeholder="Enter thesis title..." required>
                <a href="{% url 'thesis:view_thesis' %}" type="button"
                    class="absolute inset-y-0 right-0 flex items-center pr-3">
                    <svg class="w-5 h-5 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white"
                        aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path
                            d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 11.793a1 1 0 1 1-1.414 1.414L10 11.414l-2.293 2.293a1 1 0 0 1-1.414-1.414L8.586 10 6.293 7.707a1 1 0 0 1 1.414-1.414L10 8.586l2.293-2.293a1 1 0 0 1 1.414 1.414L11.414 10l2.293 2.293Z" />
                    </svg>
                </a>
            </div>
            <button type="submit"
                class="inline-flex items-center py-2.5 px-3 ml-2 text-sm font-medium text-white bg-blue-700 rounded-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                <svg class="w-4 h-4 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                    viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                </svg>Search
            </button>
        </div>
    </form>
</div>
<div class="grid grid-row md:grid-cols-3 gap-4 mb-4">
    <!-- Card for each thesis. -->
    {% for thesis in theses %}
    <div class="rounded-lg bg-gray-50 dark:bg-gray-800">
        <a href="{% url 'thesis:detail' thesis.id %}">
            <img src="{{ thesis.image.url }}" class="h-64 w-full object-cover rounded-t-lg">
            <div class="p-6 rounded-b-lg">
                <h2 class="text-lg font-normal text-gray-900 dark:text-white">{{ thesis.title }}</h2>
                <p class="text-lg font-semibold text-gray-900 dark:text-white">{{ thesis.date_published }}</p>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

thesis/templates/thesis/view_thesis_detail.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div
    class="w-full p-6 md:px-10 md:py-10 rounded-lg bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700">
    <h2 class="mb-10 text-2xl text-white font-bold text-center">Thesis Details</h2>
    <div class="flex flex-wrap">
        <!-- Left side -->
        <div class="md:basis-1/2 w-full">
            <img class="rounded-xl object-cover" src="{{ thesis.image.url }}">
        </div>
        <!-- Right side -->
        <div class="md:basis-1/2 w-full p-4 rounded-xl">
            <div class="mb-4 border-b border-gray-200 dark:border-gray-700">
                <ul class="flex flex-wrap -mb-px text-sm font-medium text-center" id="myTab"
                    data-tabs-toggle="#myTabContent" role="tablist">
                    <li class="mr-2" role="presentation">
                        <button class="inline-block p-4 border-b-2 rounded-t-lg" id="details-tab"
                            data-tabs-target="#details" type="button" role="tab" aria-controls="details"
                            aria-selected="false">Details</button>
                    </li>
                    <li class="mr-2" role="presentation">
                        <button
                            class="inline-block p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300"
                            id="description-tab" data-tabs-target="#description" type="button" role="tab"
                            aria-controls="description" aria-selected="false">Description</button>
                    </li>
                    <li class="mr-2" role="presentation">
                        <button
                            class="inline-block p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300"
                            id="author-tab" data-tabs-target="#author" type="button" role="tab" aria-controls="author"
                            aria-selected="false">Authors</button>
                    </li>
                    {% if is_staff %}
                    <li class="mr-2" role="presentation">
                        <button
                            class="inline-block p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300"
                            id="settings-tab" data-tabs-target="#settings" type="button" role="tab"
                            aria-controls="settings" aria-selected="false">Settings</button>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div id="myTabContent">
                <div class="hidden p-4 rounded-lg border border-gray-200 dark:border-gray-700" id="details"
                    role="tabpanel" aria-labelledby="details-tab">
                    <div class="flex flex-col">
                        <div class="flex flex-row">
                            <svg class="w-4 h-4 m-1 text-gray-800 dark:text-white" aria-hidden="true"
                                xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 20">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                    stroke-width="2"
                                    d="M1 18a.969.969 0 0 0 .933 1h12.134A.97.97 0 0 0 15 18M1 7V5.828a2 2 0 0 1 .586-1.414l2.828-2.828A2 2 0 0 1 5.828 1h8.239A.97.97 0 0 1 15 2v5M6 1v4a1 1 0 0 1-1 1H1m0 9v-5h1.5a1.5 1.5 0 1 1 0 3H1m12 2v-5h2m-2 3h2m-8-3v5h1.375A1.626 1.626 0 0 0 10 13.375v-1.75A1.626 1.626 0 0 0 8.375 10H7Z" />
                            </svg>
                            <span class="mb-1 text-md text-gray-500 dark:text-gray-300"> Title: {{ thesis.title
                                }}</span>
                        </div>
                        <div class="flex flex-row">
                            <svg class="w-4 h-4 m-1 text-gray-800 dark:text-white" aria-hidden="true"
                                xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                    stroke-width="2"
                                    d="M5 1v3m5-3v3m5-3v3M1 7h18M5 11h10M2 3h16a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z" />
                            </svg>
                            <span class="mb-1 text-md text-gray-500 dark:text-gray-300"> Date Published: {{
                                thesis.date_published }}</span>
                        </div>
                    </div>
                    <div class="mt-8 rounded-xl">
                        <a href="{% url 'thesis:view_file' file_location=thesis.file.path %}"
                            class="text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-200 dark:focus:ring-blue-900 font-medium rounded-lg text-sm px-5 py-2.5 inline-flex justify-center w-full text-center">View</a>
                    </div>
                </div>
                <div class="hidden p-4 rounded-lg border border-gray-200 dark:border-gray-700" id="description"
                    role="tabpanel" aria-labelledby="description-tab">
                    <div class="flex flex-row">
                        <svg class="w-4 h-4 m-1 text-gray-800 dark:text-white" aria-hidden="true"
                            xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 21 21">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="m6.072 10.072 2 2 6-4m3.586 4.314.9-.9a2 2 0 0 0 0-2.828l-.9-.9a2 2 0 0 1-.586-1.414V5.072a2 2 0 0 0-2-2H13.8a2 2 0 0 1-1.414-.586l-.9-.9a2 2 0 0 0-2.828 0l-.9.9a2 2 0 0 1-1.414.586H5.072a2 2 0 0 0-2 2v1.272a2 2 0 0 1-.586 1.414l-.9.9a2 2 0 0 0 0 2.828l.9.9a2 2 0 0 1 .586 1.414v1.272a2 2 0 0 0 2 2h1.272a2 2 0 0 1 1.414.586l.9.9a2 2 0 0 0 2.828 0l.9-.9a2 2 0 0 1 1.414-.586h1.272a2 2 0 0 0 2-2V13.8a2 2 0 0 1 .586-1.414Z" />
                        </svg>
                        <span class="mb-1 text-md text-gray-500 dark:text-gray-300"> Course: {{ thesis.course }}</span>
                    </div>
                    <div class="flex flex-row">
                        <svg class="w-4 h-4 m-1 text-gray-800 dark:text-white" aria-hidden="true"
                            xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M5 1v3m5-3v3m5-3v3M1 7h18M5 11h10M2 3h16a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z" />
                        </svg>
                        <span class="mb-1 text-md text-gray-500 dark:text-gray-300"> Date Published: {{
                            thesis.date_published }}</span>
                    </div>
                </div>
                <div class="hidden p-4 rounded-lg border border-gray-200 dark:border-gray-700" id="author"
                    role="tabpanel" aria-labelledby="author-tab">
                    {% for author in authors %}
                    <div class="flex items-center space-x-2 mb-2">
                        <div class="flex-shrink-0">
                            <img class="w-8 h-8 rounded-full object-cover" src="{{ author.author.image.url }}"
                                alt="Neil image">
                        </div>
                        <div
                            class="flex-1 min-w-0 items-center justify-between p-2 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:bg-gray-700 dark:border-gray-600">
                            <p class="text-medium text-gray-900 truncate dark:text-gray-300">
                                {{ author.author.name }}
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if is_staff %}
                <div class="hidden p-3 rounded-lg border border-gray-200 dark:border-gray-700" id="settings"
                    role="tabpanel" aria-labelledby="settings-tab">
                    <ul aria-labelledby="dropdownButton">
                        <a href="{% url 'thesis:edit' thesis.id %}">
                            <li
                                class="block px-2 py-1 text-medium text-gray-700 rounded-md hover:bg-gray-100 dark:hover:bg-gray-500 dark:text-gray-300 dark:hover:text-white">
                                <div class="inline-flex items-center justify-center group">
                                    <svg class="w-4 h-4 mr-2 text-gray-800 dark:text-white" aria-hidden="true"
                                        xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                        <g stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                            stroke-width="2">
                                            <path
                                                d="M19 11V9a1 1 0 0 0-1-1h-.757l-.707-1.707.535-.536a1 1 0 0 0 0-1.414l-1.414-1.414a1 1 0 0 0-1.414 0l-.536.535L12 2.757V2a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v.757l-1.707.707-.536-.535a1 1 0 0 0-1.414 0L2.929 4.343a1 1 0 0 0 0 1.414l.536.536L2.757 8H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h.757l.707 1.707-.535.536a1 1 0 0 0 0 1.414l1.414 1.414a1 1 0 0 0 1.414 0l.536-.535L8 17.243V18a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-.757l1.707-.708.536.536a1 1 0 0 0 1.414 0l1.414-1.414a1 1 0 0 0 0-1.414l-.535-.536.707-1.707H18a1 1 0 0 0 1-1Z" />
                                            <path d="M10 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z" />
                                        </g>
                                    </svg>Edit Thesis Detail
                                </div>
                            </li>
                        </a>
                        <a href="{% url 'thesis:add_author_in_author_list' thesis.id %}">
                            <li
                                class="block px-2 py-1 text-medium text-gray-700 rounded-md hover:bg-gray-100 dark:hover:bg-gray-500 dark:text-gray-300 dark:hover:text-white">
                                <div class="inline-flex items-center justify-center group">
                                    <svg class="w-4 h-4 mr-2 text-gray-800 dark:text-white" aria-hidden="true"
                                        xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 18">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                            stroke-width="2"
                                            d="M13 8h6m-3 3V5m-6-.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0ZM5 11h3a4 4 0 0 1 4 4v2H1v-2a4 4 0 0 1 4-4Z" />
                                    </svg>Add Author in Author List
                                </div>
                            </li>
                        </a>
                        <a href="{% url 'thesis:add_author' %}">
                            <li
                                class="block px-2 py-1 text-medium text-gray-700 rounded-md hover:bg-gray-100 dark:hover:bg-gray-500 dark:text-gray-300 dark:hover:text-white">
                                <div class="inline-flex items-center justify-center group">
                                    <svg class="w-4 h-4 mr-2 text-gray-800 dark:text-white" aria-hidden="true"
                                        xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 18">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                            stroke-width="2"
                                            d="M13 8h6m-3 3V5m-6-.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0ZM5 11h3a4 4 0 0 1 4 4v2H1v-2a4 4 0 0 1 4-4Z" />
                                    </svg>Add Author
                                </div>
                            </li>
                        </a>
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}