book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('read/', views.read_book, name='read_book'),
    path('detail/read/<int:book_primary_key>/', views.read_book_detail, name='read_book_detail'),
    path('create/', views.create_book, name='create_book'),
    path('update/<int:book_primary_key>/', views.update_book, name='update_book'),
    path('author/add/', views.add_author, name='add_author'),
    path('author-in-list/add/<int:primary_key>/', views.add_author_in_author_list, name='add_author_in_author_list'),
]

django_library_management/urls.py
from django.contrib import admin
from django.urls import path, include
# Imports for showing images.
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('__reload__/', include('django_browser_reload.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user-profile/', include('user_profile.urls')),
    path('address/', include('address.urls')),
    path('course/', include('course.urls')),
    path('thesis/', include('thesis.urls')),
    path('book/', include('book.urls')),
    path('suggestion/', include('suggestion.urls')),
    path('borrow-book/', include('borrow_book.urls')),
    path('review/', include('review.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path 
from . import views

app_name = 'profile'

urlpatterns=[
    path('', views.view_profile, name='view_profile'),
    path('update/', views.update_profile, name='update_profile'),
    path('password/update/', views.update_password, name='update_password'),
    path('address/update/', views.update_address, name='update_address'),
    path('address/update/province/load/', views.load_province, name='load_province'),
    path('address/update/city/municipality/load/', views.load_city_municipality, name='load_city_municipality'),
    path('address/update/barangay/load/', views.load_barangay, name='load_barangay'),
]

user_profile/models.py
from django.contrib.auth.models import User
from django.db import models
from course.models import Course
from address.models import Region, Province, City_Municipality, Barangay
 
class Profile(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    OTHERS = 'O'

    GENDER_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (OTHERS, 'O'),
    ]

    image = models.ImageField(upload_to='profile_images', default='default_profile_image.jpg')
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, default=OTHERS)
    student_number = models.CharField(max_length=100, unique=True, null=True)
    student_contact_no = models.CharField(max_length=15, unique=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, related_name='course_id', on_delete=models.CASCADE)
    location = models.CharField(max_length=100, blank=True)
    barangay = models.ForeignKey(Barangay, on_delete=models.SET_NULL, null=True)
    city_municipality = models.ForeignKey(City_Municipality, on_delete=models.SET_NULL, null=True)
    province = models.ForeignKey(Province, on_delete=models.SET_NULL, null=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.user.username

user_profile/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from address.models import Region, Province, City_Municipality, Barangay

@login_required
def view_profile(request):
    return render(request, 'profile/view_profile.html', {
        'title': 'Profile',
        'is_staff': request.is_staff,
    })

@login_required
def update_profile(request):
    if request.method == 'POST':
        user = request.user
        profile = user.profile

        user.first_name = request.POST.get('first_name', '')
        user.last_name = request.POST.get('last_name', '')
        user.username = request.POST.get('username', '')
        user.email = request.POST.get('email', '')

        # Validating and handling student_number and student_contact_no inputs
        student_number = request.POST.get('student_number', '')
        student_contact_no = request.POST.get('student_contact_no', '')

        if student_number:
            profile.student_number = student_number

        if student_contact_no:
            profile.student_contact_no = student_contact_no

        # Handling image upload
        if request.FILES.get('image'):
            profile.image = request.FILES['image']

        profile.save()
        user.save()
        messages.success(request, 'Success! The profile has been edited.')
        return redirect('profile:update_profile')

    return render(request, 'profile/update_profile.html', {
        'title': 'Edit Profile',
        'is_staff': request.is_staff,
    })

@login_required
def update_address(request):
    regions = Region.objects.all()

    if request.method == 'POST':
        try:
            region = request.POST['region']
            province = request.POST['province']
            city_municipality = request.POST['city_municipality']
            barangay = request.POST['barangay']
            location = request.POST['location']

            region = get_object_or_404(Region, pk=region)
            province = get_object_or_404(Province, pk=province)
            city_municipality = get_object_or_404(City_Municipality, pk=city_municipality)
            barangay = get_object_or_404(Barangay, pk=barangay)
            request.user.profile.region = region
            request.user.profile.province = province
            request.user.profile.city_municipality = city_municipality
            request.user.profile.barangay = barangay
            request.user.profile.location = location
            request.user.profile.save()

            messages.success(request, "User address updated successfully! Your changes have been saved.")
            return redirect('profile:update_address')
        except Exception as e:
            messages.error(request, f"Failed to update address. {e}")
    
    return render(request, 'profile/update_address.html', {
        'title': 'Edit User Address',
        'regions': regions,
    })

@login_required
def load_province(request):
    region = request.GET.get('region')
    provinces = Province.objects.filter(region=region)
    return render(request, 'profile/load/province_options.html', {
        'provinces': provinces,
    })

@login_required
def load_city_municipality(request):
    province = request.GET.get('province')
    city_municipalities = City_Municipality.objects.filter(province=province)
    return render(request, 'profile/load/city_municipality_options.html', {
        'city_municipalities': city_municipalities,
    })

@login_required
def load_barangay(request):
    city_municipality = request.GET.get('city_municipality')
    barangays = Barangay.objects.filter(city_municipality=city_municipality)
    return render(request, 'profile/load/barangay_options.html', {
        'barangays': barangays,
    })

@login_required
def update_password(request):
    if request.method == 'POST':
        try:
            old_password = request.POST['old_password'] 
            new_password = request.POST['new_password']
            confirm_new_password = request.POST['confirm_new_password'] 

            if request.user.check_password(old_password):
                if not request.user.check_password(new_password):
                    if new_password == confirm_new_password:
                        request.user.set_password(new_password)
                        request.user.save()
                        messages.success(request, 'Password updated successfully!')
                        return redirect('core:signin')
                    else:
                        messages.error(request, 'Failed to update password. New password does not match.')
                        return redirect('profile:update_password')
                else:
                    messages.error(request, 'Failed to update password. New password cannot be the old password.')
                    return redirect('profile:update_password')
            else:
                messages.error(request, 'Failed to update password. Old password does not match.')
                return redirect('profile:update_password')
        except Exception as e:
            messages.error(request, f'Failed to update password. {e}')
            
    return render(request, 'profile/update_password.html', {
        'title': 'Change Password',
        'is_staff': request.is_staff,
    })

user_profile/templates/profile/load/barangay_options.html
<label for="barangay" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Barangay</label>
<select name="barangay" id="barangay" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
  <option selected>Choose a barangay</option>
  {% for barangay in barangays %}
    <option value="{{ barangay.pk }}">{{ barangay.name }}</option>
  {% endfor %}
</select>

user_profile/templates/profile/load/city_municipality_options.html
<label for="city_municipality" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">City or Municipality</label>
<select name="city_municipality" id="city_municipality" hx-get="{% url 'profile:load_barangay' %}" hx-trigger="change" hx-target="#barangays"
  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
  <option selected>Choose a city/municipality</option>
  {% for city_municipality in city_municipalities %}
    <option value="{{ city_municipality.pk }}">{{ city_municipality.name }}</option>
  {% endfor %}
</select>

user_profile/templates/profile/load/province_options.html
<label for="province" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Province</label>
<select name="province" id="province" hx-get="{% url 'profile:load_city_municipality' %}" hx-trigger="change" hx-target="#city_municipalities"
  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
  <option selected>Choose a province</option>
  {% for province in provinces %}
    <option value="{{ province.pk }}">{{ province.name }}</option>
  {% endfor %}
</select>