book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('read/', views.read_book, name='read_book'),
    path('detail/read/<int:book_primary_key>/', views.read_book_detail, name='read_book_detail'),
    path('create/', views.create_book, name='create_book'),
    path('update/<int:book_primary_key>/', views.update_book, name='update_book'),
    path('author/add/', views.add_author, name='add_author'),
    path('author-in-list/add/<int:primary_key>/', views.add_author_in_author_list, name='add_author_in_author_list'),
]

django_library_management/urls.py
from django.contrib import admin
from django.urls import path, include
# Imports for showing images.
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('__reload__/', include('django_browser_reload.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user-profile/', include('user_profile.urls')),
    path('address/', include('address.urls')),
    path('course/', include('course.urls')),
    path('thesis/', include('thesis.urls')),
    path('book/', include('book.urls')),
    path('suggestion/', include('suggestion.urls')),
    path('borrow-book/', include('borrow_book.urls')),
    path('review/', include('review.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

suggestion/urls.py
from django.urls import path
from . import views

app_name = 'suggestion'

urlpatterns = [
    path('', views.view_suggestion, name='view_suggestion'),
    path('create/', views.create_suggestion, name='create_suggestion'),
    path('update/<int:primary_key>/', views.update_suggestion, name='update_suggestion'),
]

thesis/urls.py
from django.urls import path
from . import views

app_name = 'thesis'

urlpatterns = [
    path('', views.view_thesis, name='view_thesis'),
    path('detail/<int:primary_key>/', views.view_thesis_detail, name='view_thesis_detail'),
    path('add/', views.add, name='add'),
    path('edit/<int:primary_key>/', views.edit, name='edit'),
    path('author/add/', views.add_author, name='add_author'),
    path('author-in-list/add/<int:primary_key>/', views.add_author_in_author_list, name='add_author_in_author_list'),
    path('view_file/<str:file_location>/', views.view_file, name='view_file'),
]

suggestion/models.py
from django.db import models
from django.contrib.auth.models import User

class Suggestion(models.Model):
    book_title = models.CharField(max_length=255)
    comment = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

suggestion/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from .models import Suggestion
from .form import SuggestionForm

@login_required
def view_suggestion(request):
    suggestions = Suggestion.objects.filter(created_by=request.user)
    return render(request, 'suggestion/suggestion.html', {
        'title': 'Suggestion',
        'suggestions': suggestions,
        'is_staff': request.is_staff,
    })

@login_required
def create_suggestion(request):
    if request.method == 'POST':
        form = SuggestionForm(request.POST)
        if form.is_valid():
            suggestion = form.save(commit=False)
            suggestion.created_by = request.user
            suggestion.save()
            messages.success(request, 'Success! The suggestion has been added.')
            return redirect('suggestion:view_suggestion')
    else:
        form = SuggestionForm()
    return render(request, 'suggestion/form.html', {
        'title': 'Add Suggestion',
        'form': form,
        'is_staff': request.is_staff,
    })

@login_required
def update_suggestion(request, primary_key):
    suggestion = get_object_or_404(Suggestion, id=primary_key)
    if request.method == 'POST':
        form = SuggestionForm(request.POST, instance=suggestion)
        if form.is_valid():
            form.save()
            messages.success(request, 'Success! The suggestion has been edited.')
            return redirect('suggestion:view_suggestion')
    else:
        form = SuggestionForm(instance=suggestion)

    return render(request, 'suggestion/form.html', {
        'title': 'Edit Suggestion',
        'form': form,
        'is_staff': request.is_staff,
    })

suggestion/templates/suggestion/form.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="flex justify-center">
    <div class="w-full max-w-xl p-6 bg-white border border-gray-200 rounded-md shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
        <h1 class="mb-4 text-lg font-semibold text-gray-900 dark:text-white">{{ title }}</h1>
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="space-y-6 text-white">
                {% for field in form %}
                    {% if field.name == 'book_title' %}
                        <div>
                            <label for="{{ field.id_for_label }}"
                                class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ field.label }}</label>
                            <div class="flex">
                                <span
                                    class="inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border border-e-0 border-gray-300 rounded-l-lg dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
                                    <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 20">
                                        <path d="M16 14V2a2 2 0 0 0-2-2H2a2 2 0 0 0-2 2v15a3 3 0 0 0 3 3h12a1 1 0 0 0 0-2h-1v-2a2 2 0 0 0 2-2ZM4 2h2v12H4V2Zm8 16H3a1 1 0 0 1 0-2h9v2Z"/>
                                    </svg>                                   
                                </span>
                                {{ field }}
                            </div>
                        </div>
                    {% endif %}

                    {% if field.name == 'comment' %}
                        <div>
                            <label for="{{ field.id_for_label }}"
                                class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ field.label }}</label>
                            <div class="flex">
                                <span
                                    class="inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border border-e-0 border-gray-300 rounded-l-lg dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
                                    <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                                        <path d="M20 3H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h2v4a1 1 0 0 0 1.707.707L12.414 16H20a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2ZM7.5 11a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm4.5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm4.5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Z"/>
                                    </svg>                                          
                                </span>
                                {{ field }}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                <button class="w-full text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Submit</button>
            </div>
        </form>      
    </div>
</div>
{% endblock %}

suggestion/templates/suggestion/index.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="flex justify-center">
    <div class="w-full">
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <caption class="p-5 text-lg font-semibold text-left text-gray-900 bg-white dark:text-white dark:bg-gray-800">
                    Book Suggestions
                    <p class="mt-1 text-sm font-normal text-gray-500 dark:text-gray-400">Browse the list of book suggestions that the students and teachers suggested.</p>
                </caption>
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Book title
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Comment
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Created by 
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Suggested by
                        </th>
                        <th scope="col" class="px-6 py-3">
                            <span class="sr-only">Edit</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for suggestion in suggestions %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ suggestion.book_title }}
                        </th>
                        <td class="px-6 py-4">
                            {{ suggestion.comment }}
                        </td>
                        <td class="px-6 py-4">
                            {{ suggestion.created_at }}
                        </td>
                        <td class="px-6 py-4">
                            {{ suggestion.created_by.first_name }} {{ suggestion.created_by.last_name }}
                        </td>
                        <td class="px-6 py-4 text-right">
                            <a href="{% url 'suggestion:edit' suggestion.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

suggestion/templates/suggestion/suggestion.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="flex justify-center">
    <div class="w-full">
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <caption
                    class="p-5 text-lg font-semibold text-left text-gray-900 bg-white dark:text-white dark:bg-gray-800">
                    Book Suggestions
                    <p class="mt-1 text-sm font-normal text-gray-500 dark:text-gray-400">Browse the list of book
                        suggestions that the students and teachers suggested.</p>
                </caption>
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Book title
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Comment
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Created by
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Suggested by
                        </th>
                        <th scope="col" class="px-6 py-3">
                            <span class="sr-only">Edit</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for suggestion in suggestions %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ suggestion.book_title }}
                        </th>
                        <td class="px-6 py-4">
                            {{ suggestion.comment }}
                        </td>
                        <td class="px-6 py-4">
                            {{ suggestion.created_at }}
                        </td>
                        <td class="px-6 py-4">
                            {{ suggestion.created_by.first_name }} {{ suggestion.created_by.last_name }}
                        </td>
                        <td class="px-6 py-4 text-right">
                            <a href="{% url 'suggestion:update_suggestion' suggestion.id %}"
                                class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}