book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('read/', views.read_book, name='read_book'),
    path('detail/read/<int:book_primary_key>/', views.read_book_detail, name='read_book_detail'),
    path('create/', views.create_book, name='create_book'),
    path('update/<int:book_primary_key>/', views.update_book, name='update_book'),
    path('author/add/', views.add_author, name='add_author'),
    path('author-in-list/add/<int:primary_key>/', views.add_author_in_author_list, name='add_author_in_author_list'),
]

borrow_book/urls.py
from django.urls import path
from . import views

app_name = 'borrow_book'

urlpatterns = [
    path('transactions/all/read/', views.read_all_borrow_book_transactions, name='read_all_borrow_book_transactions'),
    path('transactions/read/', views.read_borrow_book_transactions, name='read_borrow_book_transactions'),
    path('borrow-request/read/', views.read_requests_to_borrow_book, name='read_requests_to_borrow_book'),
    path('borrow-request/create/<int:book_primary_key>/', views.create_request_to_borrow_book, name='create_request_to_borrow_book'),
    path('borrow-request-approve/<int:borrow_book_primary_key>/', views.approve_borrow_book_request, name='approve_borrow_book_request'),
    path('for-pickup/read/', views.read_books_for_pick_up, name='read_books_for_pick_up'),
    path('for-pickup/approve/<int:borrow_book_primary_key>/', views.approve_book_pick_up, name='approve_book_pick_up'),
    path('for-return/read/', views.read_books_for_return, name='read_books_for_return'),
    path('for-return/return/<int:borrow_book_primary_key>/', views.return_book, name='return_book'),
]

django_library_management/urls.py
from django.contrib import admin
from django.urls import path, include
# Imports for showing images.
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('__reload__/', include('django_browser_reload.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user-profile/', include('user_profile.urls')),
    path('address/', include('address.urls')),
    path('course/', include('course.urls')),
    path('thesis/', include('thesis.urls')),
    path('book/', include('book.urls')),
    path('suggestion/', include('suggestion.urls')),
    path('borrow-book/', include('borrow_book.urls')),
    path('review/', include('review.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

borrow_book/models.py
from django.db import models
from book.models import Book
from django.contrib.auth.models import User

class Borrow_Book(models.Model):
    REQUEST = 'Request' 
    BORROWED = 'Borrowed'
    PENDING = 'Pending'
    APPROVED = 'Approved'
    RETURNED = 'Returned'

    REQUEST_STATUS_CHOICES = {
        (REQUEST, 'Request'),
        (BORROWED, 'Borrowed'),
        (PENDING, 'Pending'),
        (APPROVED, 'Approved'),
        (RETURNED, 'Returned'),
    }
    
    request_status = models.CharField(max_length=15, choices=REQUEST_STATUS_CHOICES, default=REQUEST)
    request_created = models.DateTimeField(auto_now_add=True)
    pick_up_date = models.DateField(null=True)
    return_due_date = models.DateField(null=True)
    returned_date = models.DateField(null=True)
    pending_days = models.IntegerField(null=True)
    fine = models.IntegerField(null=True)
    book = models.ForeignKey(Book, on_delete=models.PROTECT)
    created_by = models.ForeignKey(User, related_name='created_by_id', on_delete=models.PROTECT)
    staff_approve = models.ForeignKey(User, related_name='staff_approve_id', on_delete=models.PROTECT, null=True)
    staff_borrow = models.ForeignKey(User, related_name='staff_borrow_id', on_delete=models.PROTECT, null=True)
    staff_return = models.ForeignKey(User, related_name='staff_return_id', on_delete=models.PROTECT, null=True)

borrow_book/forms.py
from django import forms
from .models import Borrow_Book
import datetime
today = datetime.date.today()

INPUT_CLASSES = 'rounded-r-lg bg-gray-50 border border-gray-300 text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
SELECT_AREA = 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
TEXT_AREA = 'block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
FOR_IMAGE = 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400'
CHECKBOX = 'w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600'
class BorrowBookRequestApproveForm(forms.ModelForm):
    class Meta:
        model = Borrow_Book
        fields = ['pick_up_date']
        widgets = {
            'pick_up_date': forms.SelectDateWidget(years=range(today.year, 2999), attrs={
                'class': SELECT_AREA,
            }),
        }

class BookPickUpApproveForm(forms.ModelForm):
    class Meta:
        model = Borrow_Book
        fields = ['return_due_date']
        widgets = {
            'return_due_date': forms.SelectDateWidget(years=range(today.year, 2999), attrs={
                'class': SELECT_AREA,
            }),
        }

borrow_book/views.py
from datetime import date
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from book.models import Book
from core.decorators import allow_certain_groups
from .models import Borrow_Book
from .forms import BorrowBookRequestApproveForm, BookPickUpApproveForm

@login_required()
def read_borrow_book_transactions(request):
    borrow_books = Borrow_Book.objects.filter(created_by=request.user)
    return render(request, 'borrow_book/index.html', {
        'title': 'Borrowed Books',
        'borrow_books': borrow_books,
        'is_staff': request.is_staff,
    })

@login_required()
@allow_certain_groups(['staff'])
def read_all_borrow_book_transactions(request):
    borrow_book_transactions = Borrow_Book.objects.all()
    return render(request, 'borrow_book/borrow_book_transactions.html', {
        'title': 'Transactions',
        'borrow_book_transactions': borrow_book_transactions,
        'is_staff': request.is_staff,
    })
    
@login_required()
@allow_certain_groups(['staff'])
def read_requests_to_borrow_book(request):
    borrow_books = Borrow_Book.objects.filter(request_status='Request')
    return render(request, 'borrow_book/borrow_request.html', {
        'title': 'Borrow Request',
        'borrow_books': borrow_books,
        'is_staff': request.is_staff,
    })

@login_required()
def create_request_to_borrow_book(request, book_primary_key):
    book = get_object_or_404(Book, pk=book_primary_key)
    is_borrowed = Borrow_Book.objects.filter(created_by=request.user, book=book).filter(~Q(request_status='Returned')).exists()
    if is_borrowed:
        return redirect('book:detail', primary_key=book_primary_key)
    else:
        borrow_book = Borrow_Book.objects.create(created_by=request.user, book=book)
        borrow_book.save()
        messages.success(request, f'Success! Your request to borrow the book {book.title} has been received. We will review your request and notify you shortly.')
        return redirect('borrow_book:read_borrow_book_transactions')

@login_required()
@allow_certain_groups(['staff'])
def approve_borrow_book_request(request, borrow_book_primary_key):
    transaction = get_object_or_404(Borrow_Book, pk=borrow_book_primary_key)

    if request.method == 'POST':
        form = BorrowBookRequestApproveForm(request.POST, instance=transaction)
        if form.is_valid():
            approve = form.save(commit=False)
            approve.request_status = 'Approved'
            approve.staff_approve = request.user
            approve.save()
            messages.success(request, 'Success! Borrow book request has been approved.')
            return redirect('borrow_book:read_all_borrow_book_transactions')
    else:
        form = BorrowBookRequestApproveForm(instance=transaction)
    return render(request, 'borrow_book/form.html', {
        'title': 'Borrow Book Request Approve',
        'is_staff': request.is_staff,
        'form': form,
    })

@login_required()
@allow_certain_groups(['staff'])
def read_books_for_pick_up(request):
    borrow_books = Borrow_Book.objects.filter(request_status='Approved')
    return render(request, 'borrow_book/book_pick_up.html', {
        'title': 'Borrow Request',
        'borrow_books': borrow_books,
        'is_staff': request.is_staff,
    })

@login_required()
@allow_certain_groups(['staff'])
def approve_book_pick_up(request, borrow_book_primary_key):
    transaction = get_object_or_404(Borrow_Book, pk=borrow_book_primary_key)

    if request.method == 'POST':
        form = BookPickUpApproveForm(request.POST, instance=transaction)
        if form.is_valid():
            approve = form.save(commit=False)
            approve.request_status = 'Borrowed'
            approve.staff_borrow = request.user
            approve.save()
            messages.success(request, 'Success! Book pickup has been approved.')
            return redirect('borrow_book:read_all_borrow_book_transactions')
    else:
        form = BookPickUpApproveForm(instance=transaction)
    return render(request, 'borrow_book/form.html', {
        'title': 'Book Pick Up Approve',
        'form': form,
        'is_staff': request.is_staff,
    })

@login_required()
@allow_certain_groups(['staff'])
def read_books_for_return(request):
    borrow_books = Borrow_Book.objects.filter(request_status='Borrowed')
    return render(request, 'borrow_book/return_book.html', {
        'title': 'Borrow Request',
        'borrow_books': borrow_books,
        'is_staff': request.is_staff,
    })

@login_required()
@allow_certain_groups(['staff'])
def return_book(request, borrow_book_primary_key):
    transaction = get_object_or_404(Borrow_Book, pk=borrow_book_primary_key)

    transaction.request_status = 'Returned'
    transaction.staff_return = request.user
    transaction.returned_date = date.today()
    delta = transaction.returned_date - transaction.return_due_date
    if delta.days > 0:
        transaction.pending_days = delta.days
        transaction.fine = transaction.pending_days * 20
        transaction.save()
        messages.success(request, 'Success! Book has been returned.')
        return redirect('borrow_book:read_all_borrow_book_transactions')
    else:
        transaction.pending_days = 0
        transaction.fine = 0
        transaction.save()
        messages.success(request, 'Success! Book has been returned.')
        return redirect('borrow_book:read_all_borrow_book_transactions')

borrow_book/templates/borrow_book/book_pick_up.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="flex justify-center">
    <div class="w-full">
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <caption class="p-5 text-lg font-semibold text-left text-gray-900 bg-white dark:text-white dark:bg-gray-800">
                    Book Pick up
                    <p class="mt-1 text-sm font-normal text-gray-500 dark:text-gray-400">Browse the list of schedules of books pick up.</p>
                </caption>
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Book title
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Transaction Status
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Requested by
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Pick up Date
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Staff Approved
                        </th>
                        <th scope="col" class="px-6 py-3">
                            <span class="sr-only">Edit</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for borrow_book in borrow_books %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ borrow_book.book.title }}
                        </th>
                        <td class="px-6 py-4">
                            {{ borrow_book.request_status }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.created_by.first_name }} {{ borrow_book.created_by.last_name }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.pick_up_date }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.staff_approve.first_name }} {{ borrow_book.staff_approve.last_name }}
                        </td>
                        <td class="px-6 py-4">
                            <a href="{% url 'borrow_book:approve_book_pick_up' borrow_book.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Borrow</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

borrow_book/templates/borrow_book/borrow_book_transactions.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="flex justify-center">
    <div class="w-full">
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <caption class="p-5 text-lg font-semibold text-left text-gray-900 bg-white dark:text-white dark:bg-gray-800">
                    All Borrow Book Transactions
                    <p class="mt-1 text-sm font-normal text-gray-500 dark:text-gray-400">Browse the list of all borrow books transactions.</p>
                </caption>
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Title
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Status
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Created by
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Pending Days
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Fine
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Pick up date
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Return due date
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Returned Date
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Staff Approve
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Staff Pickup
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Staff Return
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for borrow_book in borrow_book_transactions %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ borrow_book.book.title }}
                        </th>
                        <td class="px-6 py-4">
                            {{ borrow_book.request_status }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.created_by.first_name }} {{ borrow_book.created_by.last_name }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.pending_days }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.fine }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.pick_up_date }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.return_due_date }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.returned_date }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.staff_approve.first_name }} {{ borrow_book.staff_approve.last_name }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.staff_borrow.first_name }} {{ borrow_book.staff_borrow.last_name }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.staff_return.first_name }} {{ borrow_book.staff_return.last_name }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

borrow_book/templates/borrow_book/borrow_request.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="flex justify-center">
    <div class="w-full">
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <caption class="p-5 text-lg font-semibold text-left text-gray-900 bg-white dark:text-white dark:bg-gray-800">
                    Borrow Book Request
                    <p class="mt-1 text-sm font-normal text-gray-500 dark:text-gray-400">Browse the list of all borrow books request from students and teachers.</p>
                </caption>
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Book title
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Transaction Status
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Requested by
                        </th>
                        <th scope="col" class="px-6 py-3">
                            <span class="sr-only">Edit</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for borrow_book in borrow_books %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ borrow_book.book.title }}
                        </th>
                        <td class="px-6 py-4">
                            {{ borrow_book.request_status }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.created_by.first_name }} {{ borrow_book.created_by.last_name }}
                        </td>
                        <td class="px-6 py-4">
                            <a href="{% url 'borrow_book:approve_borrow_book_request' borrow_book.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Approve</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

borrow_book/templates/borrow_book/form.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="flex justify-center">
    <div class="w-full max-w-xl p-6 bg-white border border-gray-200 rounded-md shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
        <h1 class="mb-4 text-lg font-semibold text-gray-900 dark:text-white">{{ title }}</h1>
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="space-y-6 text-white">
                {% for field in form %}
                    {% if field.name == 'pick_up_date' %}
                        <div class="col-span-2">
                            <label for="{{ field.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ field.label }}</label>
                            <div class="flex items-center gap-4">
                                {{ form.pick_up_date }}
                            </div>
                        </div>
                    {% endif %}

                    {% if field.name == 'return_due_date' %}
                        <div class="col-span-2">
                            <label for="{{ field.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ field.label }}</label>
                            <div class="flex items-center gap-4">
                                {{ form.return_due_date }}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                <button class="w-full text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Submit</button>
            </div>
        </form>      
    </div>
</div>
{% endblock %}

borrow_book/templates/borrow_book/index.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="flex justify-center">
    <div class="w-full">
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <caption class="p-5 text-lg font-semibold text-left text-gray-900 bg-white dark:text-white dark:bg-gray-800">
                    Borrow Book Transaction
                    <p class="mt-1 text-sm font-normal text-gray-500 dark:text-gray-400">Browse the list of all borrow books transactions.</p>
                </caption>
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Title
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Status
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Pending Days
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Fine
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Pick up date
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Return due date
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Returned Date
                        </th>
                        <th scope="col" class="px-6 py-3">
                            <span class="sr-only">Review</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for borrow_book in borrow_books %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ borrow_book.book.title }}
                        </th>
                        <td class="px-6 py-4">
                            {{ borrow_book.request_status }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.pending_days }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.fine }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.pick_up_date }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.return_due_date }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.returned_date }}
                        </td>
                        <td class="px-6 py-4 text-right">
                            <a href="{% url 'review:add' borrow_book.book.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Review</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

borrow_book/templates/borrow_book/return_book.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="flex justify-center">
    <div class="w-full">
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <caption class="p-5 text-lg font-semibold text-left text-gray-900 bg-white dark:text-white dark:bg-gray-800">
                    Book Return
                    <p class="mt-1 text-sm font-normal text-gray-500 dark:text-gray-400">Browse the list of schedules of books return.</p>
                </caption>
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Book title
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Transaction Status
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Requested by
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Return Due Date
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Staff Process Borrow
                        </th>
                        <th scope="col" class="px-6 py-3">
                            <span class="sr-only">Edit</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for borrow_book in borrow_books %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ borrow_book.book.title }}
                        </th>
                        <td class="px-6 py-4">
                            {{ borrow_book.request_status }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.created_by.first_name }} {{ borrow_book.created_by.last_name }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.return_due_date }}
                        </td>
                        <td class="px-6 py-4">
                            {{ borrow_book.staff_borrow.first_name }} {{ borrow_book.staff_borrow.last_name }}
                        </td>
                        <td class="px-6 py-4">
                            <a href="{% url 'borrow_book:return_book' borrow_book.id%}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Return</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}